# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wsmp.ui'
#
# Created: Tue Nov 17 13:26:11 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainTab = QtGui.QTabWidget(self.centralWidget)
        self.mainTab.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTab.sizePolicy().hasHeightForWidth())
        self.mainTab.setSizePolicy(sizePolicy)
        self.mainTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainTab.setAutoFillBackground(False)
        self.mainTab.setTabPosition(QtGui.QTabWidget.North)
        self.mainTab.setDocumentMode(False)
        self.mainTab.setTabsClosable(False)
        self.mainTab.setMovable(True)
        self.mainTab.setObjectName("mainTab")
        self.signalTab = QtGui.QWidget()
        self.signalTab.setObjectName("signalTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.signalTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.measureHLayout = QtGui.QHBoxLayout()
        self.measureHLayout.setObjectName("measureHLayout")
        self.measureGrid = QtGui.QGridLayout()
        self.measureGrid.setContentsMargins(-1, -1, -1, 0)
        self.measureGrid.setObjectName("measureGrid")
        self.cqiFrame = QtGui.QFrame(self.signalTab)
        self.cqiFrame.setAutoFillBackground(False)
        self.cqiFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cqiFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.cqiFrame.setObjectName("cqiFrame")
        self.cqiLayout = QtGui.QVBoxLayout(self.cqiFrame)
        self.cqiLayout.setObjectName("cqiLayout")
        self.cqiLabel = QtGui.QLabel(self.cqiFrame)
        self.cqiLabel.setObjectName("cqiLabel")
        self.cqiLayout.addWidget(self.cqiLabel)
        self.cqiPlot = MatplotlibWidget(self.cqiFrame)
        self.cqiPlot.setObjectName("cqiPlot")
        self.cqiLayout.addWidget(self.cqiPlot)
        self.measureGrid.addWidget(self.cqiFrame, 0, 0, 1, 1)
        self.delayFrame = QtGui.QFrame(self.signalTab)
        self.delayFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.delayFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.delayFrame.setObjectName("delayFrame")
        self.delayLayout = QtGui.QVBoxLayout(self.delayFrame)
        self.delayLayout.setObjectName("delayLayout")
        self.delayLabel = QtGui.QLabel(self.delayFrame)
        self.delayLabel.setObjectName("delayLabel")
        self.delayLayout.addWidget(self.delayLabel)
        self.delayPlot = MatplotlibWidget(self.delayFrame)
        self.delayPlot.setObjectName("delayPlot")
        self.delayLayout.addWidget(self.delayPlot)
        self.measureGrid.addWidget(self.delayFrame, 1, 1, 1, 1)
        self.throughputFrame = QtGui.QFrame(self.signalTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.throughputFrame.sizePolicy().hasHeightForWidth())
        self.throughputFrame.setSizePolicy(sizePolicy)
        self.throughputFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.throughputFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.throughputFrame.setObjectName("throughputFrame")
        self.throughputLayout = QtGui.QVBoxLayout(self.throughputFrame)
        self.throughputLayout.setObjectName("throughputLayout")
        self.throughputLabel = QtGui.QLabel(self.throughputFrame)
        self.throughputLabel.setObjectName("throughputLabel")
        self.throughputLayout.addWidget(self.throughputLabel)
        self.throughputPlot = MatplotlibWidget(self.throughputFrame)
        self.throughputPlot.setObjectName("throughputPlot")
        self.throughputLayout.addWidget(self.throughputPlot)
        self.measureGrid.addWidget(self.throughputFrame, 3, 0, 1, 1)
        self.rssiFrame = QtGui.QFrame(self.signalTab)
        self.rssiFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.rssiFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.rssiFrame.setObjectName("rssiFrame")
        self.rssiLayout = QtGui.QVBoxLayout(self.rssiFrame)
        self.rssiLayout.setObjectName("rssiLayout")
        self.rssiLabel = QtGui.QLabel(self.rssiFrame)
        self.rssiLabel.setObjectName("rssiLabel")
        self.rssiLayout.addWidget(self.rssiLabel)
        self.rssiPlot = MatplotlibWidget(self.rssiFrame)
        self.rssiPlot.setObjectName("rssiPlot")
        self.rssiLayout.addWidget(self.rssiPlot)
        self.measureGrid.addWidget(self.rssiFrame, 1, 0, 1, 1)
        self.cinrFrame = QtGui.QFrame(self.signalTab)
        self.cinrFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cinrFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.cinrFrame.setObjectName("cinrFrame")
        self.cinrLayout = QtGui.QVBoxLayout(self.cinrFrame)
        self.cinrLayout.setObjectName("cinrLayout")
        self.cinrLabel = QtGui.QLabel(self.cinrFrame)
        self.cinrLabel.setObjectName("cinrLabel")
        self.cinrLayout.addWidget(self.cinrLabel)
        self.cinrPlot = MatplotlibWidget(self.cinrFrame)
        self.cinrPlot.setObjectName("cinrPlot")
        self.cinrLayout.addWidget(self.cinrPlot)
        self.measureGrid.addWidget(self.cinrFrame, 0, 1, 1, 1)
        self.otherDataFrame = QtGui.QFrame(self.signalTab)
        self.otherDataFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.otherDataFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.otherDataFrame.setObjectName("otherDataFrame")
        self.otherDataLayout = QtGui.QVBoxLayout(self.otherDataFrame)
        self.otherDataLayout.setObjectName("otherDataLayout")
        self.otherDataText = QtGui.QTextBrowser(self.otherDataFrame)
        self.otherDataText.setObjectName("otherDataText")
        self.otherDataLayout.addWidget(self.otherDataText)
        self.measureGrid.addWidget(self.otherDataFrame, 3, 1, 1, 1)
        self.measureHLayout.addLayout(self.measureGrid)
        self.tagAndRemarksLayout = QtGui.QVBoxLayout()
        self.tagAndRemarksLayout.setObjectName("tagAndRemarksLayout")
        self.tagLabel = QtGui.QLabel(self.signalTab)
        self.tagLabel.setObjectName("tagLabel")
        self.tagAndRemarksLayout.addWidget(self.tagLabel)
        self.tagLineEdit = QtGui.QLineEdit(self.signalTab)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.tagAndRemarksLayout.addWidget(self.tagLineEdit)
        self.remarksLabel = QtGui.QLabel(self.signalTab)
        self.remarksLabel.setObjectName("remarksLabel")
        self.tagAndRemarksLayout.addWidget(self.remarksLabel)
        self.remarksTextEdit = QtGui.QTextEdit(self.signalTab)
        self.remarksTextEdit.setObjectName("remarksTextEdit")
        self.tagAndRemarksLayout.addWidget(self.remarksTextEdit)
        self.measureHLayout.addLayout(self.tagAndRemarksLayout)
        self.verticalLayout_2.addLayout(self.measureHLayout)
        self.sendMeasureHLayout = QtGui.QHBoxLayout()
        self.sendMeasureHLayout.setSpacing(6)
        self.sendMeasureHLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.sendMeasureHLayout.setObjectName("sendMeasureHLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.sendMeasureHLayout.addItem(spacerItem)
        self.sendMeasureButton = QtGui.QPushButton(self.signalTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendMeasureButton.sizePolicy().hasHeightForWidth())
        self.sendMeasureButton.setSizePolicy(sizePolicy)
        self.sendMeasureButton.setCheckable(False)
        self.sendMeasureButton.setAutoDefault(True)
        self.sendMeasureButton.setDefault(False)
        self.sendMeasureButton.setFlat(False)
        self.sendMeasureButton.setObjectName("sendMeasureButton")
        self.sendMeasureHLayout.addWidget(self.sendMeasureButton)
        self.verticalLayout_2.addLayout(self.sendMeasureHLayout)
        self.mainTab.addTab(self.signalTab, "")
        self.apcTab = QtGui.QWidget()
        self.apcTab.setObjectName("apcTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.apcTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.apcClientGroupBox = QtGui.QGroupBox(self.apcTab)
        self.apcClientGroupBox.setObjectName("apcClientGroupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.apcClientGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.apcClientInterfaceLabel = QtGui.QLabel(self.apcClientGroupBox)
        self.apcClientInterfaceLabel.setObjectName("apcClientInterfaceLabel")
        self.verticalLayout_8.addWidget(self.apcClientInterfaceLabel)
        self.apcClientInterfaceScrollArea = QtGui.QScrollArea(self.apcClientGroupBox)
        self.apcClientInterfaceScrollArea.setWidgetResizable(True)
        self.apcClientInterfaceScrollArea.setObjectName("apcClientInterfaceScrollArea")
        self.apcClientInterfaceScrollAreaWidgetContents = QtGui.QWidget(self.apcClientInterfaceScrollArea)
        self.apcClientInterfaceScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 960, 116))
        self.apcClientInterfaceScrollAreaWidgetContents.setObjectName("apcClientInterfaceScrollAreaWidgetContents")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.apcClientInterfaceScrollAreaWidgetContents)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.apcClientInterfaceListView = QtGui.QListView(self.apcClientInterfaceScrollAreaWidgetContents)
        self.apcClientInterfaceListView.setObjectName("apcClientInterfaceListView")
        self.horizontalLayout_6.addWidget(self.apcClientInterfaceListView)
        self.apcClientInterfaceScrollArea.setWidget(self.apcClientInterfaceScrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.apcClientInterfaceScrollArea)
        self.apcClientSsidFormLayout = QtGui.QFormLayout()
        self.apcClientSsidFormLayout.setObjectName("apcClientSsidFormLayout")
        self.apcClientSsidLabel = QtGui.QLabel(self.apcClientGroupBox)
        self.apcClientSsidLabel.setObjectName("apcClientSsidLabel")
        self.apcClientSsidFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.apcClientSsidLabel)
        self.apcClientSsidLineEdit = QtGui.QLineEdit(self.apcClientGroupBox)
        self.apcClientSsidLineEdit.setReadOnly(True)
        self.apcClientSsidLineEdit.setObjectName("apcClientSsidLineEdit")
        self.apcClientSsidFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.apcClientSsidLineEdit)
        self.verticalLayout_8.addLayout(self.apcClientSsidFormLayout)
        self.verticalLayout_7.addWidget(self.apcClientGroupBox)
        self.apcAccessPointGroupBox = QtGui.QGroupBox(self.apcTab)
        self.apcAccessPointGroupBox.setObjectName("apcAccessPointGroupBox")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.apcAccessPointGroupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.apcAccessPointMSNFormLayout = QtGui.QFormLayout()
        self.apcAccessPointMSNFormLayout.setObjectName("apcAccessPointMSNFormLayout")
        self.apcAccessPointModelLabel = QtGui.QLabel(self.apcAccessPointGroupBox)
        self.apcAccessPointModelLabel.setObjectName("apcAccessPointModelLabel")
        self.apcAccessPointMSNFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.apcAccessPointModelLabel)
        self.apcAccessPointModelLineEdit = QtGui.QLineEdit(self.apcAccessPointGroupBox)
        self.apcAccessPointModelLineEdit.setObjectName("apcAccessPointModelLineEdit")
        self.apcAccessPointMSNFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.apcAccessPointModelLineEdit)
        self.apcAccessPointSerialNumberLabel = QtGui.QLabel(self.apcAccessPointGroupBox)
        self.apcAccessPointSerialNumberLabel.setObjectName("apcAccessPointSerialNumberLabel")
        self.apcAccessPointMSNFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.apcAccessPointSerialNumberLabel)
        self.apcAccessPointSerialNumberLineEdit = QtGui.QLineEdit(self.apcAccessPointGroupBox)
        self.apcAccessPointSerialNumberLineEdit.setObjectName("apcAccessPointSerialNumberLineEdit")
        self.apcAccessPointMSNFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.apcAccessPointSerialNumberLineEdit)
        self.verticalLayout_11.addLayout(self.apcAccessPointMSNFormLayout)
        self.apcAccessPointPositionGroupBox = QtGui.QGroupBox(self.apcAccessPointGroupBox)
        self.apcAccessPointPositionGroupBox.setObjectName("apcAccessPointPositionGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.apcAccessPointPositionGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.apcAccessPointPositionLatitudeLabel = QtGui.QLabel(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionLatitudeLabel.setObjectName("apcAccessPointPositionLatitudeLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.apcAccessPointPositionLatitudeLabel)
        self.apcAccessPointPositionLatitudeLineEdit = QtGui.QLineEdit(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionLatitudeLineEdit.setObjectName("apcAccessPointPositionLatitudeLineEdit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.apcAccessPointPositionLatitudeLineEdit)
        self.apcAccessPointPositionLongitude = QtGui.QLabel(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionLongitude.setObjectName("apcAccessPointPositionLongitude")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.apcAccessPointPositionLongitude)
        self.apcAccessPointLongitudeLineEdit = QtGui.QLineEdit(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointLongitudeLineEdit.setObjectName("apcAccessPointLongitudeLineEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.apcAccessPointLongitudeLineEdit)
        self.apcAccessPointPositionHeigth = QtGui.QLabel(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionHeigth.setObjectName("apcAccessPointPositionHeigth")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.apcAccessPointPositionHeigth)
        self.apcAccessPointPositionHeigthLineEdit = QtGui.QLineEdit(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionHeigthLineEdit.setObjectName("apcAccessPointPositionHeigthLineEdit")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.apcAccessPointPositionHeigthLineEdit)
        self.getCurrentGpsPositionAsAccessPointButtonSpacerLayout = QtGui.QHBoxLayout()
        self.getCurrentGpsPositionAsAccessPointButtonSpacerLayout.setObjectName("getCurrentGpsPositionAsAccessPointButtonSpacerLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.getCurrentGpsPositionAsAccessPointButtonSpacerLayout.addItem(spacerItem1)
        self.apcAccessPointPositionButton = QtGui.QPushButton(self.apcAccessPointPositionGroupBox)
        self.apcAccessPointPositionButton.setObjectName("apcAccessPointPositionButton")
        self.getCurrentGpsPositionAsAccessPointButtonSpacerLayout.addWidget(self.apcAccessPointPositionButton)
        self.formLayout_4.setLayout(3, QtGui.QFormLayout.FieldRole, self.getCurrentGpsPositionAsAccessPointButtonSpacerLayout)
        self.verticalLayout_11.addWidget(self.apcAccessPointPositionGroupBox)
        self.verticalLayout_7.addWidget(self.apcAccessPointGroupBox)
        self.apcServerGroupBox = QtGui.QGroupBox(self.apcTab)
        self.apcServerGroupBox.setObjectName("apcServerGroupBox")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.apcServerGroupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.apcServerParamsButtonLayout = QtGui.QHBoxLayout()
        self.apcServerParamsButtonLayout.setObjectName("apcServerParamsButtonLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.apcServerParamsButtonLayout.addItem(spacerItem2)
        self.apcServerParamsButton = QtGui.QPushButton(self.apcServerGroupBox)
        self.apcServerParamsButton.setCheckable(True)
        self.apcServerParamsButton.setObjectName("apcServerParamsButton")
        self.apcServerParamsButtonLayout.addWidget(self.apcServerParamsButton)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.apcServerParamsButtonLayout)
        self.apcServerAddressLineEdit = QtGui.QLineEdit(self.apcServerGroupBox)
        self.apcServerAddressLineEdit.setObjectName("apcServerAddressLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.apcServerAddressLineEdit)
        self.apcServerPortLineEdit = QtGui.QLineEdit(self.apcServerGroupBox)
        self.apcServerPortLineEdit.setObjectName("apcServerPortLineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.apcServerPortLineEdit)
        self.apcServerAddressLabel = QtGui.QLabel(self.apcServerGroupBox)
        self.apcServerAddressLabel.setObjectName("apcServerAddressLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.apcServerAddressLabel)
        self.apcServerPortLabel = QtGui.QLabel(self.apcServerGroupBox)
        self.apcServerPortLabel.setObjectName("apcServerPortLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.apcServerPortLabel)
        self.verticalLayout_14.addLayout(self.formLayout_2)
        self.verticalLayout_7.addWidget(self.apcServerGroupBox)
        self.apcServerPositionGroupBox = QtGui.QGroupBox(self.apcTab)
        self.apcServerPositionGroupBox.setObjectName("apcServerPositionGroupBox")
        self.formLayout_5 = QtGui.QFormLayout(self.apcServerPositionGroupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.apcServerPositionLatitudeLabel = QtGui.QLabel(self.apcServerPositionGroupBox)
        self.apcServerPositionLatitudeLabel.setObjectName("apcServerPositionLatitudeLabel")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.apcServerPositionLatitudeLabel)
        self.apcServerPositionLatitudeLineEdit = QtGui.QLineEdit(self.apcServerPositionGroupBox)
        self.apcServerPositionLatitudeLineEdit.setObjectName("apcServerPositionLatitudeLineEdit")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.apcServerPositionLatitudeLineEdit)
        self.apcServerPositionLongitudeLabel = QtGui.QLabel(self.apcServerPositionGroupBox)
        self.apcServerPositionLongitudeLabel.setObjectName("apcServerPositionLongitudeLabel")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.apcServerPositionLongitudeLabel)
        self.apcServerPositionLongitudeLineEdit = QtGui.QLineEdit(self.apcServerPositionGroupBox)
        self.apcServerPositionLongitudeLineEdit.setObjectName("apcServerPositionLongitudeLineEdit")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.apcServerPositionLongitudeLineEdit)
        self.apcServerPositionHeightLabel = QtGui.QLabel(self.apcServerPositionGroupBox)
        self.apcServerPositionHeightLabel.setObjectName("apcServerPositionHeightLabel")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.apcServerPositionHeightLabel)
        self.apcServerPositionHeightLineEdit = QtGui.QLineEdit(self.apcServerPositionGroupBox)
        self.apcServerPositionHeightLineEdit.setObjectName("apcServerPositionHeightLineEdit")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.apcServerPositionHeightLineEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.apcServerPositionButton = QtGui.QPushButton(self.apcServerPositionGroupBox)
        self.apcServerPositionButton.setObjectName("apcServerPositionButton")
        self.horizontalLayout_2.addWidget(self.apcServerPositionButton)
        self.formLayout_5.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.apcServerPositionGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.mainTab.addTab(self.apcTab, "")
        self.dbTab = QtGui.QWidget()
        self.dbTab.setObjectName("dbTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dbTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dbSetupGroupBox = QtGui.QGroupBox(self.dbTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbSetupGroupBox.sizePolicy().hasHeightForWidth())
        self.dbSetupGroupBox.setSizePolicy(sizePolicy)
        self.dbSetupGroupBox.setObjectName("dbSetupGroupBox")
        self.formLayout = QtGui.QFormLayout(self.dbSetupGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.dbAddressLabel = QtGui.QLabel(self.dbSetupGroupBox)
        self.dbAddressLabel.setObjectName("dbAddressLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.dbAddressLabel)
        self.dbAddressLineEdit = QtGui.QLineEdit(self.dbSetupGroupBox)
        self.dbAddressLineEdit.setObjectName("dbAddressLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dbAddressLineEdit)
        self.dbLoginLabel = QtGui.QLabel(self.dbSetupGroupBox)
        self.dbLoginLabel.setObjectName("dbLoginLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.dbLoginLabel)
        self.dbLoginLineEdit = QtGui.QLineEdit(self.dbSetupGroupBox)
        self.dbLoginLineEdit.setObjectName("dbLoginLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dbLoginLineEdit)
        self.dbPasswordLabel = QtGui.QLabel(self.dbSetupGroupBox)
        self.dbPasswordLabel.setObjectName("dbPasswordLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.dbPasswordLabel)
        self.dbPasswordLineEdit = QtGui.QLineEdit(self.dbSetupGroupBox)
        self.dbPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.dbPasswordLineEdit.setObjectName("dbPasswordLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dbPasswordLineEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.dbConnectButton = QtGui.QPushButton(self.dbSetupGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbConnectButton.sizePolicy().hasHeightForWidth())
        self.dbConnectButton.setSizePolicy(sizePolicy)
        self.dbConnectButton.setCheckable(True)
        self.dbConnectButton.setObjectName("dbConnectButton")
        self.horizontalLayout_3.addWidget(self.dbConnectButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.dbSetupGroupBox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.mainTab.addTab(self.dbTab, "")
        self.bluetoothTab = QtGui.QWidget()
        self.bluetoothTab.setObjectName("bluetoothTab")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.bluetoothTab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.bluetoothDeviceGroupBox = QtGui.QGroupBox(self.bluetoothTab)
        self.bluetoothDeviceGroupBox.setObjectName("bluetoothDeviceGroupBox")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.bluetoothDeviceGroupBox)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.bluetoothDeviceCurrentlyUsedFormLayout = QtGui.QFormLayout()
        self.bluetoothDeviceCurrentlyUsedFormLayout.setObjectName("bluetoothDeviceCurrentlyUsedFormLayout")
        self.bluetoothDeviceCurrentlyUsedLabel = QtGui.QLabel(self.bluetoothDeviceGroupBox)
        self.bluetoothDeviceCurrentlyUsedLabel.setObjectName("bluetoothDeviceCurrentlyUsedLabel")
        self.bluetoothDeviceCurrentlyUsedFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.bluetoothDeviceCurrentlyUsedLabel)
        self.bluetoothDeviceCurrentlyUsedLineEdit = QtGui.QLineEdit(self.bluetoothDeviceGroupBox)
        self.bluetoothDeviceCurrentlyUsedLineEdit.setReadOnly(True)
        self.bluetoothDeviceCurrentlyUsedLineEdit.setObjectName("bluetoothDeviceCurrentlyUsedLineEdit")
        self.bluetoothDeviceCurrentlyUsedFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.bluetoothDeviceCurrentlyUsedLineEdit)
        self.verticalLayout_13.addLayout(self.bluetoothDeviceCurrentlyUsedFormLayout)
        self.bluetoothDeviceScrollArea = QtGui.QScrollArea(self.bluetoothDeviceGroupBox)
        self.bluetoothDeviceScrollArea.setWidgetResizable(True)
        self.bluetoothDeviceScrollArea.setObjectName("bluetoothDeviceScrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.bluetoothDeviceScrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 960, 210))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bluetoothDeviceListView = QtGui.QListView(self.scrollAreaWidgetContents)
        self.bluetoothDeviceListView.setObjectName("bluetoothDeviceListView")
        self.horizontalLayout.addWidget(self.bluetoothDeviceListView)
        self.bluetoothDeviceScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.bluetoothDeviceScrollArea)
        self.bluetoothDeviceScanConnectLayout = QtGui.QHBoxLayout()
        self.bluetoothDeviceScanConnectLayout.setObjectName("bluetoothDeviceScanConnectLayout")
        self.bluetoothDeviceScanButton = QtGui.QPushButton(self.bluetoothDeviceGroupBox)
        self.bluetoothDeviceScanButton.setObjectName("bluetoothDeviceScanButton")
        self.bluetoothDeviceScanConnectLayout.addWidget(self.bluetoothDeviceScanButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bluetoothDeviceScanConnectLayout.addItem(spacerItem7)
        self.bluetoothDeviceConnectButton = QtGui.QPushButton(self.bluetoothDeviceGroupBox)
        self.bluetoothDeviceConnectButton.setObjectName("bluetoothDeviceConnectButton")
        self.bluetoothDeviceScanConnectLayout.addWidget(self.bluetoothDeviceConnectButton)
        self.verticalLayout_13.addLayout(self.bluetoothDeviceScanConnectLayout)
        self.verticalLayout_12.addWidget(self.bluetoothDeviceGroupBox)
        self.bluetoothParsedGroupBox = QtGui.QGroupBox(self.bluetoothTab)
        self.bluetoothParsedGroupBox.setObjectName("bluetoothParsedGroupBox")
        self.formLayout_3 = QtGui.QFormLayout(self.bluetoothParsedGroupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.bluetoothParsedHeightLabel = QtGui.QLabel(self.bluetoothParsedGroupBox)
        self.bluetoothParsedHeightLabel.setObjectName("bluetoothParsedHeightLabel")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.bluetoothParsedHeightLabel)
        self.bluetoothParsedHeightLineEdit = QtGui.QLineEdit(self.bluetoothParsedGroupBox)
        self.bluetoothParsedHeightLineEdit.setReadOnly(True)
        self.bluetoothParsedHeightLineEdit.setObjectName("bluetoothParsedHeightLineEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.bluetoothParsedHeightLineEdit)
        self.bluetoothParsedLatitudeLineEdit = QtGui.QLineEdit(self.bluetoothParsedGroupBox)
        self.bluetoothParsedLatitudeLineEdit.setReadOnly(True)
        self.bluetoothParsedLatitudeLineEdit.setObjectName("bluetoothParsedLatitudeLineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.bluetoothParsedLatitudeLineEdit)
        self.bluetoothParsedLongitudeLineEdit = QtGui.QLineEdit(self.bluetoothParsedGroupBox)
        self.bluetoothParsedLongitudeLineEdit.setReadOnly(True)
        self.bluetoothParsedLongitudeLineEdit.setObjectName("bluetoothParsedLongitudeLineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.bluetoothParsedLongitudeLineEdit)
        self.bluetoothParsedLongitudeLabel = QtGui.QLabel(self.bluetoothParsedGroupBox)
        self.bluetoothParsedLongitudeLabel.setObjectName("bluetoothParsedLongitudeLabel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.bluetoothParsedLongitudeLabel)
        self.bluetoothParsedLatitudeLabel = QtGui.QLabel(self.bluetoothParsedGroupBox)
        self.bluetoothParsedLatitudeLabel.setObjectName("bluetoothParsedLatitudeLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.bluetoothParsedLatitudeLabel)
        self.verticalLayout_12.addWidget(self.bluetoothParsedGroupBox)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.mainTab.addTab(self.bluetoothTab, "")
        self.langTab = QtGui.QWidget()
        self.langTab.setObjectName("langTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.langTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.langEnglishButton = QtGui.QPushButton(self.langTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.langEnglishButton.sizePolicy().hasHeightForWidth())
        self.langEnglishButton.setSizePolicy(sizePolicy)
        self.langEnglishButton.setObjectName("langEnglishButton")
        self.verticalLayout_3.addWidget(self.langEnglishButton)
        self.langJapaneseButton = QtGui.QPushButton(self.langTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.langJapaneseButton.sizePolicy().hasHeightForWidth())
        self.langJapaneseButton.setSizePolicy(sizePolicy)
        self.langJapaneseButton.setFlat(False)
        self.langJapaneseButton.setObjectName("langJapaneseButton")
        self.verticalLayout_3.addWidget(self.langJapaneseButton)
        self.mainTab.addTab(self.langTab, "")
        self.verticalLayout_6.addWidget(self.mainTab)
        MainWindow.setCentralWidget(self.centralWidget)
        self.tagLabel.setBuddy(self.tagLineEdit)
        self.remarksLabel.setBuddy(self.remarksTextEdit)
        self.apcClientInterfaceLabel.setBuddy(self.apcClientInterfaceListView)
        self.apcAccessPointModelLabel.setBuddy(self.apcAccessPointModelLineEdit)
        self.apcAccessPointSerialNumberLabel.setBuddy(self.apcAccessPointSerialNumberLineEdit)
        self.apcAccessPointPositionLatitudeLabel.setBuddy(self.apcAccessPointPositionLatitudeLineEdit)
        self.apcAccessPointPositionLongitude.setBuddy(self.apcAccessPointLongitudeLineEdit)
        self.apcAccessPointPositionHeigth.setBuddy(self.apcAccessPointPositionHeigthLineEdit)
        self.dbAddressLabel.setBuddy(self.dbAddressLineEdit)
        self.dbLoginLabel.setBuddy(self.dbLoginLineEdit)
        self.dbPasswordLabel.setBuddy(self.dbPasswordLineEdit)
        self.bluetoothDeviceCurrentlyUsedLabel.setBuddy(self.bluetoothDeviceCurrentlyUsedLineEdit)
        self.bluetoothParsedHeightLabel.setBuddy(self.bluetoothParsedHeightLineEdit)
        self.bluetoothParsedLongitudeLabel.setBuddy(self.bluetoothParsedLongitudeLineEdit)
        self.bluetoothParsedLatitudeLabel.setBuddy(self.bluetoothParsedLatitudeLineEdit)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(1)
        QtCore.QObject.connect(self.dbAddressLineEdit, QtCore.SIGNAL("returnPressed()"), self.dbConnectButton.toggle)
        QtCore.QObject.connect(self.dbLoginLineEdit, QtCore.SIGNAL("returnPressed()"), self.dbConnectButton.toggle)
        QtCore.QObject.connect(self.dbPasswordLineEdit, QtCore.SIGNAL("returnPressed()"), self.dbConnectButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "WiFi Signal Measure Provider", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setToolTip(QtGui.QApplication.translate("MainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.cqiLabel.setText(QtGui.QApplication.translate("MainWindow", "CQI", None, QtGui.QApplication.UnicodeUTF8))
        self.delayLabel.setText(QtGui.QApplication.translate("MainWindow", "DELAY", None, QtGui.QApplication.UnicodeUTF8))
        self.throughputLabel.setText(QtGui.QApplication.translate("MainWindow", "THROUGHPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.rssiLabel.setText(QtGui.QApplication.translate("MainWindow", "RSSI", None, QtGui.QApplication.UnicodeUTF8))
        self.cinrLabel.setText(QtGui.QApplication.translate("MainWindow", "CINR", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLabel.setText(QtGui.QApplication.translate("MainWindow", "EXPERIMENT NAME TAG", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksLabel.setText(QtGui.QApplication.translate("MainWindow", "REMARKS", None, QtGui.QApplication.UnicodeUTF8))
        self.sendMeasureButton.setText(QtGui.QApplication.translate("MainWindow", "Send Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setTabText(self.mainTab.indexOf(self.signalTab), QtGui.QApplication.translate("MainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.apcClientGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.apcClientInterfaceLabel.setText(QtGui.QApplication.translate("MainWindow", "Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.apcClientSsidLabel.setText(QtGui.QApplication.translate("MainWindow", "Current connection SSID", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Access Point", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointModelLabel.setText(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointSerialNumberLabel.setText(QtGui.QApplication.translate("MainWindow", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointPositionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointPositionLatitudeLabel.setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointPositionLongitude.setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointPositionHeigth.setText(QtGui.QApplication.translate("MainWindow", "Heigth", None, QtGui.QApplication.UnicodeUTF8))
        self.apcAccessPointPositionButton.setText(QtGui.QApplication.translate("MainWindow", "GET CURRENT GPS POSITION AS ACCESS POINT POSITION", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Measure Server", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerParamsButton.setText(QtGui.QApplication.translate("MainWindow", "USE THESE PARAMETERS", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPortLabel.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPositionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPositionLatitudeLabel.setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPositionLongitudeLabel.setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPositionHeightLabel.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.apcServerPositionButton.setText(QtGui.QApplication.translate("MainWindow", "GET CURRENT GPS POSITION AS MEASURE SERVER POSITION", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setTabText(self.mainTab.indexOf(self.apcTab), QtGui.QApplication.translate("MainWindow", "AP/Client", None, QtGui.QApplication.UnicodeUTF8))
        self.dbSetupGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.dbAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.dbLoginLabel.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.dbPasswordLabel.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.dbConnectButton.setText(QtGui.QApplication.translate("MainWindow", "CONNECT", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setTabText(self.mainTab.indexOf(self.dbTab), QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothDeviceGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothDeviceCurrentlyUsedLabel.setText(QtGui.QApplication.translate("MainWindow", "Currently used ", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothDeviceScanButton.setText(QtGui.QApplication.translate("MainWindow", "SCAN", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothDeviceConnectButton.setText(QtGui.QApplication.translate("MainWindow", "CONNECT", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothParsedGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Parsed GPS values", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothParsedHeightLabel.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothParsedLongitudeLabel.setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.bluetoothParsedLatitudeLabel.setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setTabText(self.mainTab.indexOf(self.bluetoothTab), QtGui.QApplication.translate("MainWindow", "Bluetooth (GPS)", None, QtGui.QApplication.UnicodeUTF8))
        self.langEnglishButton.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.langJapaneseButton.setText(QtGui.QApplication.translate("MainWindow", "日本語", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTab.setTabText(self.mainTab.indexOf(self.langTab), QtGui.QApplication.translate("MainWindow", "Language / 言語", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
